I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/episodes/episode3.rpy", line 612, in script
    arthur_nlteche "Я посмотрю внимательно все твои записи и схемы, и затем можем приступать к работе!"
Exception: Sayer 'arthur_nlteche' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/episodes/episode3.rpy", line 612, in script
    arthur_nlteche "Я посмотрю внимательно все твои записи и схемы, и затем можем приступать к работе!"
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'arthur_nlteche' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
ERAIDAproject 3.0
Sat Dec 24 20:07:00 2022
